# Generated by Django 2.1.7 on 2019-04-05 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deux', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multifactorauth',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='multifactorauth_multi_factor_auth', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
